# Local Kubernetes cluster configuration
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: visionflow
nodes:
- role: control-plane
  image: kindest/node:v1.28.0
  extraPortMappings:
  - containerPort: 30000
    hostPort: 8000
    protocol: TCP
  - containerPort: 30001
    hostPort: 8001
    protocol: TCP
  - containerPort: 30002
    hostPort: 8002
    protocol: TCP
  - containerPort: 30090
    hostPort: 9090
    protocol: TCP
  - containerPort: 30300
    hostPort: 3000
    protocol: TCP
- role: worker
  image: kindest/node:v1.28.0
  extraMounts:
  - hostPath: ./models
    containerPath: /models
  - hostPath: ./generated
    containerPath: /generated
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
