# Local development with GPU support
version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: visionflow-postgres-local
    environment:
      POSTGRES_DB: visionflow
      POSTGRES_USER: visionflow
      POSTGRES_PASSWORD: visionflow_local
    volumes:
      - postgres_local_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U visionflow"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Redis Cache and Queue
  redis:
    image: redis:7-alpine
    container_name: visionflow-redis-local
    command: redis-server --appendonly yes
    volumes:
      - redis_local_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # MinIO Object Storage (local S3)
  minio:
    image: minio/minio:latest
    container_name: visionflow-minio-local
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_local_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: visionflow-api-local
    environment:
      - ENVIRONMENT=local
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=visionflow
      - DB_USER=visionflow
      - DB_PASSWORD=visionflow_local
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - STORAGE_ENDPOINT=minio:9000
      - STORAGE_ACCESS_KEY=minio
      - STORAGE_SECRET_KEY=minio123
      - STORAGE_BUCKET=visionflow-local
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - LOG_LEVEL=debug
      - VERTEX_AI_PROJECT=${VERTEX_AI_PROJECT:-visionflow-gcp-project}
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/gcp/service-account.json
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - ./models:/app/models
      - ./generated:/app/generated
      - ./logs:/app/logs
      - ~/.gcp/visionflow-service-account.json:/etc/gcp/service-account.json:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # GPU Video Generation Service
  generation-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.generation
    container_name: visionflow-generation-local
    environment:
      - ENVIRONMENT=local
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=visionflow
      - DB_USER=visionflow
      - DB_PASSWORD=visionflow_local
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MODEL_DEVICE=auto
      - MODEL_CACHE_DIR=/app/models
      - WAN_MODEL_PATH=multimodalart/wan2-1-fast
      - MAX_CONCURRENT_GENERATIONS=1
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - CUDA_VISIBLE_DEVICES=0
    ports:
      - "8002:8002"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./models:/app/models
      - ./generated:/app/generated
      - ./logs:/app/logs
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    restart: unless-stopped

  # LangChain Orchestration Service
  orchestration-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.orchestrator
    container_name: visionflow-orchestrator-local
    environment:
      - ENVIRONMENT=local
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=visionflow
      - DB_USER=visionflow
      - DB_PASSWORD=visionflow_local
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - VERTEX_AI_PROJECT=${VERTEX_AI_PROJECT:-visionflow-gcp-project}
      - VERTEX_AI_REGION=us-central1
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/gcp/service-account.json
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ~/.gcp/visionflow-service-account.json:/etc/gcp/service-account.json:ro
    restart: unless-stopped

  # Prometheus Metrics (local monitoring)
  prometheus:
    image: prom/prometheus:latest
    container_name: visionflow-prometheus-local
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    volumes:
      - ./docker/prometheus-local.yml:/etc/prometheus/prometheus.yml
      - prometheus_local_data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped

  # Grafana Dashboard (local monitoring)
  grafana:
    image: grafana/grafana:latest
    container_name: visionflow-grafana-local
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_local_data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  postgres_local_data:
    driver: local
  redis_local_data:
    driver: local
  minio_local_data:
    driver: local
  prometheus_local_data:
    driver: local
  grafana_local_data:
    driver: local

networks:
  default:
    name: visionflow-local
